import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import React from 'react'
import { formatCategoryLabel } from './categories'

const COLORS = {
  primary: '#4F46E5',
  primaryDark: '#3730A3',
  text: '#0F172A',
  muted: '#64748B',
  border: '#E2E8F0',
  bg: '#F8FAFC',
  green: '#10B981',
  amber: '#F59E0B',
  slate: '#94A3B8',
  rowAlt: '#F1F5F9',
}

const styles = StyleSheet.create({
  page: { paddingTop: 36, paddingBottom: 48, paddingHorizontal: 36, fontSize: 10, color: COLORS.text, fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  brandBox: { backgroundColor: COLORS.primary, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, color: 'white', fontSize: 11, fontFamily: 'Helvetica-Bold' },
  brand: { fontFamily: 'Helvetica-Bold', fontSize: 14 },
  small: { fontSize: 9, color: COLORS.muted },
  h1: { fontFamily: 'Helvetica-Bold', fontSize: 22, marginBottom: 4 },
  h2: { fontFamily: 'Helvetica-Bold', fontSize: 16, marginBottom: 10 },
  sub: { fontSize: 11, color: COLORS.muted, marginBottom: 14 },
  metaGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 },
  metaCell: { width: '50%', paddingVertical: 6, paddingRight: 8 },
  metaLabel: { fontSize: 9, color: COLORS.muted, marginBottom: 2 },
  metaValue: { fontSize: 13, fontFamily: 'Helvetica-Bold' },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  statCard: { flex: 1, backgroundColor: COLORS.bg, padding: 12, borderRadius: 6, borderWidth: 1, borderColor: COLORS.border },
  statLabel: { fontSize: 9, color: COLORS.muted },
  statValue: { fontFamily: 'Helvetica-Bold', fontSize: 20, marginTop: 2, color: COLORS.primaryDark },
  table: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 4, overflow: 'hidden' },
  trh: { flexDirection: 'row', backgroundColor: COLORS.primary },
  th: { padding: 6, fontSize: 9, fontFamily: 'Helvetica-Bold', color: 'white' },
  tr: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: COLORS.border },
  trAlt: { backgroundColor: COLORS.rowAlt },
  td: { padding: 6, fontSize: 9 },
  badge: { paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3, fontSize: 8, color: 'white', fontFamily: 'Helvetica-Bold' },
  footer: { position: 'absolute', bottom: 18, left: 36, right: 36, fontSize: 8, color: COLORS.muted, textAlign: 'center' },
  pageNumber: { position: 'absolute', bottom: 18, right: 36, fontSize: 8, color: COLORS.muted },
  empty: { padding: 14, textAlign: 'center', color: COLORS.muted, fontSize: 10 },
  legend: { flexDirection: 'row', marginTop: 8, marginBottom: 6, gap: 8 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  disclaimer: { marginTop: 20, padding: 10, borderWidth: 1, borderColor: COLORS.border, borderRadius: 4, backgroundColor: COLORS.bg, fontSize: 9, color: COLORS.muted },
  bullet: { flexDirection: 'row', marginBottom: 6 },
  bulletDot: { width: 16, fontFamily: 'Helvetica-Bold', color: COLORS.primary },
})

const chanceColor = (c) => ((c === 'High' || c === 'Safe') ? COLORS.green : c === 'Possible' ? COLORS.amber : COLORS.slate)
const chanceLabel = (c) => ((c === 'High' || c === 'Safe') ? 'Safe' : c)

const Header = ({ subtitle }) => (
  <View style={styles.header} fixed>
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
      <Text style={styles.brandBox}>KCET 2026</Text>
      <Text style={styles.brand}>College Predictor</Text>
    </View>
    <Text style={styles.small}>{subtitle}</Text>
  </View>
)

const Footer = () => (
  <>
    <Text style={styles.footer} fixed>
      www.kcetpredictor.in  ·  Confidential premium report  ·  Generated by KCET Predictor 2026
    </Text>
    <Text style={styles.pageNumber} fixed render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
  </>
)

const ChanceBadge = ({ chance }) => (
  <Text style={[styles.badge, { backgroundColor: chanceColor(chance) }]}>{chanceLabel(chance)}</Text>
)

const BranchTable = ({ rows }) => {
  if (!rows.length) {
    return <View style={styles.table}><Text style={styles.empty}>No colleges in this bucket.</Text></View>
  }
  return (
    <View style={styles.table}>
      <View style={styles.trh}>
        <Text style={[styles.th, { width: '52%' }]}>College</Text>
        <Text style={[styles.th, { width: '12%' }]}>Tier</Text>
        <Text style={[styles.th, { width: '22%', textAlign: 'right' }]}>Previous Cutoff</Text>
        <Text style={[styles.th, { width: '14%' }]}>Chance</Text>
      </View>
      {rows.map((r, i) => (
        <View style={[styles.tr, i % 2 === 1 ? styles.trAlt : null]} key={`${r.college_code}-${i}`} wrap={false}>
          <View style={{ width: '52%', padding: 6 }}>
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>{r.college_name}</Text>
            <Text style={{ fontSize: 8, color: COLORS.muted, marginTop: 1 }}>{r.city} · {r.college_code} · {r.course_code} — {r.course_name}</Text>
          </View>
          <Text style={[styles.td, { width: '12%' }]}>{r.tier}</Text>
          <Text style={[styles.td, { width: '22%', textAlign: 'right' }]}>{Number(r.closing_rank).toLocaleString()}</Text>
          <View style={[styles.td, { width: '14%' }]}>
            <ChanceBadge chance={r.chance} />
          </View>
        </View>
      ))}
    </View>
  )
}

const BranchesTable = ({ rows }) => {
  if (!rows.length) {
    return <View style={styles.table}><Text style={styles.empty}>No colleges obtainable.</Text></View>
  }
  return (
    <View style={styles.table}>
      <View style={styles.trh}>
        <Text style={[styles.th, { width: '38%' }]}>College</Text>
        <Text style={[styles.th, { width: '10%' }]}>Tier</Text>
        <Text style={[styles.th, { width: '52%' }]}>Available Branches</Text>
      </View>
      {rows.map((c, i) => (
        <View style={[styles.tr, i % 2 === 1 ? styles.trAlt : null]} key={c.college_code} wrap={false}>
          <View style={{ width: '38%', padding: 6 }}>
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>{c.college_name}</Text>
            <Text style={{ fontSize: 8, color: COLORS.muted, marginTop: 1 }}>{c.city} · {c.college_code}</Text>
          </View>
          <Text style={[styles.td, { width: '10%' }]}>{c.tier}</Text>
          <View style={{ width: '52%', padding: 6 }}>
            <Text style={{ fontSize: 9 }}>
              {c.courses.map((co) => `${co.course_code} (₹${co.closing_rank.toLocaleString()})`).join(', ')}
            </Text>
          </View>
        </View>
      ))}
    </View>
  )
}

function ReportDocument({ input, sectionA, sectionB }) {
  const dream = sectionA.filter((r) => r.chance === 'Dream')
  const possible = sectionA.filter((r) => r.chance === 'Possible')
  const high = sectionA.filter((r) => r.chance === 'High')
  const totalColleges = sectionB.length
  const totalBranches = sectionB.reduce((sum, c) => sum + c.courses.length, 0)
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
  const sub = `Premium Report · ${dateStr}`
  const catLabel = formatCategoryLabel(input.category)

  return (
    <Document title="KCET Predictor Report" author="KCET Predictor 2026">
      {/* Page 1: Cover */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h1}>Your Personalized College Report</Text>
        <Text style={styles.sub}>Based on KCET 2024 closing ranks; predictions for 2026 counselling.</Text>

        <View style={styles.metaGrid}>
          <View style={styles.metaCell}>
            <Text style={styles.metaLabel}>KCET Rank</Text>
            <Text style={styles.metaValue}>{Number(input.rank).toLocaleString()}</Text>
          </View>
          <View style={styles.metaCell}>
            <Text style={styles.metaLabel}>Category</Text>
            <Text style={styles.metaValue}>{catLabel}</Text>
          </View>
          <View style={styles.metaCell}>
            <Text style={styles.metaLabel}>Course (Selected)</Text>
            <Text style={styles.metaValue}>{input.course_name || input.course}</Text>
          </View>
          <View style={styles.metaCell}>
            <Text style={styles.metaLabel}>Round</Text>
            <Text style={styles.metaValue}>{input.round}</Text>
          </View>
          <View style={styles.metaCell}>
            <Text style={styles.metaLabel}>Generated On</Text>
            <Text style={styles.metaValue}>{dateStr}</Text>
          </View>
        </View>

        <View style={styles.statsRow}>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Total Colleges Predicted</Text>
            <Text style={styles.statValue}>{totalColleges}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Obtainable Branches</Text>
            <Text style={styles.statValue}>{totalBranches}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Safe / Possible / Dream</Text>
            <Text style={styles.statValue}>{high.length} / {possible.length} / {dream.length}</Text>
          </View>
        </View>

        <Text style={[styles.h2, { marginTop: 22 }]}>What’s inside</Text>
        <View style={styles.bullet}><Text style={styles.bulletDot}>1.</Text><Text>Dream Colleges — a stretch but possible (Page 2)</Text></View>
        <View style={styles.bullet}><Text style={styles.bulletDot}>2.</Text><Text>Possible Colleges — realistic targets (Page 3)</Text></View>
        <View style={styles.bullet}><Text style={styles.bulletDot}>3.</Text><Text>Safe Colleges (High Chance) — strong safety net (Page 4)</Text></View>
        <View style={styles.bullet}><Text style={styles.bulletDot}>4.</Text><Text>Top Colleges & All Obtainable Branches (Page 5)</Text></View>
        <View style={styles.bullet}><Text style={styles.bulletDot}>5.</Text><Text>Suggested KCET Option-Entry Order (Page 6)</Text></View>

        <View style={styles.disclaimer}>
          <Text>Disclaimer: Predictions are based on previous year cutoffs and do not guarantee admission. Always verify with KEA before final submission.</Text>
        </View>
        <Footer />
      </Page>

      {/* Page 2: Dream Colleges */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h2}>Dream Colleges</Text>
        <Text style={styles.sub}>Selected course — these cutoffs are above your rank but worth listing as ambitious choices.</Text>
        <BranchTable rows={dream} />
        <Footer />
      </Page>

      {/* Page 3: Possible Colleges */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h2}>Possible Colleges</Text>
        <Text style={styles.sub}>Selected course — your rank is within 10% of the closing cutoff. Realistic targets.</Text>
        <BranchTable rows={possible} />
        <Footer />
      </Page>

      {/* Page 4: Safe Colleges (High Chance) */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h2}>Safe Colleges (High Chance)</Text>
        <Text style={styles.sub}>Selected course — your rank is comfortably better than these cutoffs (≤ 0.85×). Strong safety net for option entry.</Text>
        <BranchTable rows={high} />
        <Footer />
      </Page>

      {/* Page 5: Top Colleges & All Obtainable Branches */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h2}>Top Colleges & All Obtainable Branches</Text>
        <Text style={styles.sub}>Every High or Possible branch across all colleges. Sorted by tier.</Text>
        <BranchesTable rows={sectionB} />
        <Footer />
      </Page>

      {/* Page 6: Suggested KCET Option Entry Order */}
      <Page size="A4" style={styles.page}>
        <Header subtitle={sub} />
        <Text style={styles.h2}>Suggested KCET Option-Entry Order</Text>
        <Text style={styles.sub}>
          KEA recommends putting Safe options (High Chance) at the top, followed by Possible options, then a few Dream options at the bottom. Lock as many slots as you can.
        </Text>
        <SuggestedOrder dream={dream} possible={possible} high={high} sectionB={sectionB} />
        <View style={styles.disclaimer}>
          <Text>Disclaimer: Predictions are based on previous year cutoffs and do not guarantee admission. Always verify with KEA before final option entry.</Text>
        </View>
        <Footer />
      </Page>
    </Document>
  )
}

function SuggestedOrder({ dream, possible, high, sectionB }) {
  // Build a single ranked list: for each college (Section B), pick its best branch per chance.
  // We use sectionA-filtered per chance for the selected course PLUS Section B branches for the option list.
  // Strategy: list all branches we'd recommend, ordered by chance priority then tier then cutoff.
  const recommendations = []
  for (const college of sectionB) {
    for (const co of college.courses) {
      recommendations.push({
        college_name: college.college_name,
        college_code: college.college_code,
        tier: college.tier,
        course_code: co.course_code,
        course_name: co.course_name,
        closing_rank: co.closing_rank,
        chance: co.chance,
      })
    }
  }
  // Add Dream items from sectionA so user sees ambitious picks too
  for (const d of dream) {
    recommendations.push({
      college_name: d.college_name,
      college_code: d.college_code,
      tier: d.tier,
      course_code: d.course_code,
      course_name: d.course_name,
      closing_rank: d.closing_rank,
      chance: 'Dream',
    })
  }
  const order = { High: 0, Safe: 0, Possible: 1, Dream: 2 }
  recommendations.sort((a, b) => {
    if (order[a.chance] !== order[b.chance]) return order[a.chance] - order[b.chance]
    const ta = parseInt(String(a.tier).replace(/\D/g, '')) || 9
    const tb = parseInt(String(b.tier).replace(/\D/g, '')) || 9
    if (ta !== tb) return ta - tb
    return a.closing_rank - b.closing_rank
  })
  const limited = recommendations.slice(0, 60)

  return (
    <View style={styles.table}>
      <View style={styles.trh}>
        <Text style={[styles.th, { width: '8%' }]}>#</Text>
        <Text style={[styles.th, { width: '14%' }]}>Priority</Text>
        <Text style={[styles.th, { width: '46%' }]}>College</Text>
        <Text style={[styles.th, { width: '12%' }]}>Tier</Text>
        <Text style={[styles.th, { width: '20%' }]}>Branch</Text>
      </View>
      {limited.map((r, i) => (
        <View style={[styles.tr, i % 2 === 1 ? styles.trAlt : null]} key={`${r.college_code}-${r.course_code}-${i}`} wrap={false}>
          <Text style={[styles.td, { width: '8%' }]}>{i + 1}</Text>
          <View style={[styles.td, { width: '14%' }]}>
            <ChanceBadge chance={r.chance} />
          </View>
          <View style={{ width: '46%', padding: 6 }}>
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>{r.college_name}</Text>
            <Text style={{ fontSize: 8, color: COLORS.muted, marginTop: 1 }}>{r.college_code}</Text>
          </View>
          <Text style={[styles.td, { width: '12%' }]}>{r.tier}</Text>
          <View style={{ width: '20%', padding: 6 }}>
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>{r.course_code}</Text>
            <Text style={{ fontSize: 8, color: COLORS.muted }}>cutoff {Number(r.closing_rank).toLocaleString()}</Text>
          </View>
        </View>
      ))}
    </View>
  )
}

export async function generateReportPdf({ input, sectionA, sectionB }) {
  const doc = <ReportDocument input={input} sectionA={sectionA} sectionB={sectionB} />
  const buffer = await renderToBuffer(doc)
  return buffer
}
